
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mvwgqegiuyyznyoodzxl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im12d2dxZWdpdXl5em55b29kenhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzMDMwMDMsImV4cCI6MjA1Nzg3OTAwM30.7rBLDbxdU5V564HR9QL6WhoDE-P_Ey74-BsbX0cAEzQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export type TarefaPriority = 'low' | 'normal' | 'high';
export type TarefaStatus = 'pending' | 'completed';

export type Tarefa = {
  id: string;
  user_id: string;
  title: string;
  description: string | null;
  due_date: string;
  priority: TarefaPriority;
  status: TarefaStatus;
  created_at: string;
  updated_at: string | null;
};

export type Fazenda = {
  id: string;
  nome: string;
  area_hectare: number | null;
  coordenadas: string | null;
  cidade: string | null;
  estado: string | null;
  pais: string | null;
  user_id: string;
  created_at: string;
  updated_at: string;
};

// Create a type for the get_user_tasks RPC function
export type GetUserTasksParams = {
  user_id_param: string;
};

// Add the custom functions to the Database type to properly type RPC calls
type CustomSupabaseClient = ReturnType<typeof createClient<Database>> & {
  rpc<T = any>(fn: 'get_user_tasks', params: GetUserTasksParams): {
    select: (...args: any[]) => { returns: <RT>() => { data: RT | null; error: any } };
    returns: <RT>() => Promise<{ data: RT | null; error: any }>;
  };
};

// Export the typed supabase client
export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY
) as CustomSupabaseClient;
