// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mvwgqegiuyyznyoodzxl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im12d2dxZWdpdXl5em55b29kenhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzMDMwMDMsImV4cCI6MjA1Nzg3OTAwM30.7rBLDbxdU5V564HR9QL6WhoDE-P_Ey74-BsbX0cAEzQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);